### ISSUE TITLE
Blank Data returned from AdaptivePaymentsService "Pay" function

### ISSUE THREAD

**Issue by dandawson87** [paypal/adaptivepayments-sdk-php#100]
I am getting the following object back from the pay function. The "PaymentExecStatus" is ERROR but I get no actual reason or list back from it.

Pay response: 
`{"responseEnvelope":{"timestamp":"2018-04-03T17:31:42.813-07:00","ack":"Success","correlationId":"395e95a2a380f","build":"45566028"},"payKey":"AP-9RY80221FF646480H","paymentExecStatus":"ERROR","payErrorList":null,"paymentInfoList":null,"sender":null,"defaultFundingPlan":null,"warningDataList":null,"error":null}`

**Comment by bluk** [comment]
You will need to contact [PayPal Technical Support](https://www.paypal-techsupport.com/) to help debug this issue since it seems to be directly related to your production account.
