### ISSUE TITLE
stable-php5.3 branch has duplicate libraries

### ISSUE THREAD

**Issue by indeyets** [paypal/adaptivepayments-sdk-php#30]
Here: https://github.com/paypal/adaptivepayments-sdk-php/tree/stable-php5.3/lib/PayPal/Types you can see both `AP` and `ap`, `Common` and `common` directories.

What's even worse is that they are not fully synced:

```
$ diff -ru vendor/paypal/adaptivepayments-sdk-php/lib/PayPal/Types/ap vendor/paypal/adaptivepayments-sdk-php/lib/PayPal/Types/AP
Only in vendor/paypal/adaptivepayments-sdk-php/lib/PayPal/Types/ap: PhoneNumber.php
Only in vendor/paypal/adaptivepayments-sdk-php/lib/PayPal/Types/ap: ShippingAddressInfo.php
```

**Comment by Korri** [comment]
Where are we on this, the library works on windows because it isn't case sensitive and thus merges the folders, but faild on linux `Fatal error: Class 'PayPal\Types\AP\ShippingAddressInfo' not found` because the `ShippingAddressInfo` class is in the `ap` folder and not `AP`

**Comment by jaypatel512** [comment]
Fixed in https://github.com/paypal/adaptivepayments-sdk-php/pull/53
