### ISSUE TITLE
install.php

### ISSUE THREAD

**Issue by mrnicholas78** [paypal/adaptivepayments-sdk-php#35]
I am referring to http://paypal.github.io/sdk/#adaptive-payments

Without composer
curl https://raw.github.com/paypal/adaptivepayments-sdk-php/stable-php5.3/samples/install.php | php

Where can I download this install.php

Kindly advise.

**Comment by ppmtscory** [comment]
Everything should be available within the repo and you can simply run that statement on the command line.
