### ISSUE TITLE
how to set a custom theme on Payment page?

### ISSUE THREAD

**Issue by Rah1x** [paypal/adaptivepayments-sdk-php#45]
I am trying to setup Paypal Adaptive Payment and I have multiple problems... Right now I am focusing on "Simple Payment" (which I would assume will function similar to the Express Checkout).

1) How to set custom theme on the payment page, as defined in "Customize your Payment Page" on Paypal>Profile>Selling Tools

2) How do I enable Guest Checkout a this step? Or do they always have to have a paypal account?

3) Is there a way to set NOSHIPPING=1 in Adaptive Payment just as its done on Express Checkout? 

4) How do I setup Item names in the cart list at paypal payment page? Like we do on express checkout...

**Comment by ppmtscory** [comment]
@Rah1x 
1) You would set the settings in the API and not in the account profile.  Please see `displayOptions` within [SetPaymentOptions](https://developer.paypal.com/docs/classic/api/adaptive-payments/SetPaymentOptions_API_Operation/)
2) Guest Checkout (where available) is enabled by default *unless* you are passing in a `senderEmail`, using Preapprovals, or using MPL.
3) Please see the `senderOptions` fields within [SetPaymentOptions](https://developer.paypal.com/docs/classic/api/adaptive-payments/SetPaymentOptions_API_Operation/) for requesting and/or passing shipping address fields
4) Please see the `receiverOptions` -> `invoiceData` fields within [SetPaymentOptions](https://developer.paypal.com/docs/classic/api/adaptive-payments/SetPaymentOptions_API_Operation/) for passing in Item Details
