### ISSUE TITLE
How to do partial refund in delayed chained paypal

### ISSUE THREAD

**Issue by YaminLawar** [paypal/adaptivepayments-sdk-php#47]
Hello 

I am trying for partial refund in delayed paypal i am using this library for adaptive payments. But in refund there is no option or demo for partial refund, when i use refund file available in Library it always do full refund

so please help for partial refund for multiple user

**Comment by tomwhipple** [comment]
I'm not sure exactly what is being asked, but the [Adaptive Payment refund documentation](https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-payments/Refund_API_Operation/) may provide some additional info. 

Since this issue is so old I'm going to close it.
