### ISSUE TITLE
Add the item description to my adaptive payment request

### ISSUE THREAD

**Issue by shinesoftware** [paypal/adaptivepayments-sdk-php#48]
Hi guys,

how have I to add a description of the item at paypal payment page by the adaptive method? I need to complete the payment information like in this image: 

![ec-custom-orderdetails2](https://cloud.githubusercontent.com/assets/1553035/5887270/1ff0d790-a3c6-11e4-9a38-256535b9c17a.gif)

In the paypal documentation:  https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/pp_adaptivepayments.pdf I have found the setPaymentOptions() method but I have not realized how to use it. Any code sample?

I have read this thread and seems to me that it is a little bit difficult set the right data: https://github.com/paypal/adaptivepayments-sdk-ruby/issues/10

Thanks

**Comment by pp-randy** [comment]
Item details can be specified using setPaymentOptions; however, you also need to use the embedded flow.  The above if you have 1 receiver you would supply the paykey to setPaymentOptions and have one receiver in the receiverOptions array. Line items can then be specified in invoiceData setting the items array values.

It would look like this:
![ap_lineitems](https://cloud.githubusercontent.com/assets/6819909/9879560/8c6dab44-5b8d-11e5-95b5-d39a084441ea.png)

SetPaymentOptions:
https://developer.paypal.com/docs/classic/api/adaptive-payments/SetPaymentOptions_API_Operation/

Embedded flow: 
https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-embeddedPayment-curl-etc/

**Comment by imzers** [comment]
So... this item-details cannot be used if using chained payment? The chained payment i mean have primary receiver and the secondary receiver, thank you

**Comment by pp-randy** [comment]
You still can, it would look like this for the payer to your primary, you set this with the SetPaymentOptions method.  Your Pay method would be actionType=CREATE.

**Comment by imzers** [comment]
Thank you randy,
We now already using this PP-Adaptive as one of our merchant payment gateway, just wonder if want to show item-details in user-consent should using Flow Action, cannot using redirect method.

**Comment by pp-randy** [comment]
I think you are asking if this works for redirect method.  No, line items only work using the embedded flow.

**Comment by Buttdroid** [comment]
what about parallel payments? I’m using the setPaymentOptions without any error including 2 receivers and related items data. When going to login and execute the payment I just see the total amout near each receiver. No item is shown. Any idea?
