### ISSUE TITLE
create payment and execute later

### ISSUE THREAD

**Issue by astroanu** [paypal/adaptivepayments-sdk-php#56]
1. in SimpleSamples i used the ChainedPay.php example. When a payment is complete the user get directed back to my website. but no parameters are passed to the page? how to keep track of payKey ?

2. same example if i use CREATE instead of PAY the transaction seems to still count as PAY. When i try to execute with the payKey it says payKey XXXX has already been used to make a payment. So CREATE request also gets executed automatically  ? what kind of implementation is this ?

**Comment by jaypatel512** [comment]
You could potentially do this using newer REST APIs : https://developer.paypal.com/docs/integration/direct/capture-payment/

The SDK for Rest API in PHP is available here: https://github.com/paypal/PayPal-PHP-SDK

**Comment by astroanu** [comment]
but the adaptive payments documentation says i can do that ? I tried the rest api as well. when using the rest api it said i cant use an email. can you guys maintain a more clear documentation and an API.? this is horrible
