### ISSUE TITLE
Got an error with Pay action ! 

### ISSUE THREAD

**Issue by sachy123** [paypal/adaptivepayments-sdk-php#62]
ResponseEnvelope.timestamp=2016-01-04T00%3A45%3A03.276-08%3A00&responseEnvelope.ack=Failure&responseEnvelope.correlationId=6a576cb860acb&responseEnvelope.build=17820627&error(0).errorId=520002&error(0).domain=PLATFORM&error(0).subdomain=Application&error(0).severity=Error&error(0).category=Application&error(0).message=Internal+Error

**Comment by pp-randy** [comment]
The logs appear that this was using a preapproval key, but the key was not associated with the API user of the Pay request. 

Were you using a preapproval key for the pay request?

**Comment by sachy123** [comment]
Thank you pp-randy
I solved the issue. it was regarding the application id which was not present in the configuration file.
