### ISSUE TITLE
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by maciejklowan** [paypal/adaptivepayments-sdk-php#63]
I went through your tutorial: https://devtools-paypal.com/guide/ap_chained_payment/php?interactive=ON&env=sandbox and I am receiving error like in the title. Below I am attaching you full stack trace.

Fatal error: Uncaught exception 'PayPal\Exception\PPConnectionException' with message 'error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure' in /_test/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPHttpConnection.php:91 Stack trace: #0 /_test/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPAPIService.php(66): PayPal\Core\PPHttpConnection->execute('requestEnvelope...') #1 /_test/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPBaseService.php(82): PayPal\Core\PPAPIService->makeRequest('Pay', Object(PayPal\Types\AP\PayRequest), NULL) #2 /_test/vendor/paypal/adaptivepayments-sdk-php/lib/PayPal/Service/AdaptivePaymentsService.php(182): PayPal\Core\PPBaseService->call('AdaptivePayment...', 'Pay', Object(PayPal\Types\AP\PayRequest), NULL) #3 /_test/front/paypal/chainedPayment.php(35): PayPal\Service\AdaptivePaymentsService->Pay(Object(PayPal\Types\AP\PayRequest)) #4 {main} thrown in /_test/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPHttpConnection.php on line 91

What should I do? I've changed CURLOPT_SSLVERSION =>  CURL_SSLVERSION_TLSv1

**Comment by AnatolyAstapov** [comment]
same problem
install with composer "paypal/sdk-core-php": "dev-stable"

get auth link  - its ok 
$apicontext = new \PPApiContext(array('mode' => 'sandbox')); 
        $PalPalAuthLink = \PPOpenIdSession::getAuthorizationUrl(
            $this->config->paypal["redirect_url"],
            array('openid'),
            $this->config->paypal["client_id"],
            $apicontext
        );
its ok,

when try change code to token :
$apicontext = new \PPApiContext(array('mode' => 'sandbox'));
            $params = array(
                'client_id' => $this->config->paypal["client_id"],
                'client_secret' => $this->config->paypal["client_secret"],
                'code' => $this->session->get("authCode")
            );
            $token = \PPOpenIdTokeninfo::createFromAuthorizationCode($params,$apicontext);

php error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

try add 
 \PPHttpConfig::$DEFAULT_CURL_OPTS["CURLOPT_SSLVERSION"] =  (any types trys) 0,1,2,3
 \PPHttpConfig::$DEFAULT_CURL_OPTS["CURLOPT_SSL_CIPHER_LIST"] = 'SSLv3';

problem still exists

help please

**Comment by yaraujo** [comment]
I'm facing the same issue when trying to setup a local environment, I believe this is not a problem on the code (I have the same code running properly on a different server). 

This is probably related to this (https://github.com/paypal/adaptivepayments-sdk-php#tlsv12-update) but, I believe it requires a setup on Apache to only allow TLS communications, I'm still trying to compare what's different on the other server, that works.

Hope it helps somehow.

**Comment by Omnitasker** [comment]
I have a same problem too, if I use code from example, it will give me handshake error, I tried changing 
mode to TLS  ( altough, my website is not  at https) and I get error could not resolve host "AdaptivePayments", somehow it does not even get an url "https://svcs.sandbox.paypal.com/".

I would understand that handshake error is happening due to server configuration, but then wy does the paypal test runned from my website gives me - PayPal_Connection_OKbool(true).

Please give us any response!

**Comment by codeswholesale** [comment]
Hey,

Code below works for me:

`<?php
include "../vendor/autoload.php";

$payRequest = new \PayPal\Types\AP\PayRequest();

$receiver = array();
$receiver[0] = new \PayPal\Types\AP\Receiver();
$receiver[0]->amount = doubleval($file_price) * 0.03;
$receiver[0]->email = "";

$receiver[1] = new \PayPal\Types\AP\Receiver();
$receiver[1]->amount = doubleval($file_price);
$receiver[1]->email = "";
$receiver[1]->primary = "true";
$receiverList = new \PayPal\Types\AP\ReceiverList($receiver);
$payRequest->receiverList = $receiverList;

$requestEnvelope = new \PayPal\Types\Common\RequestEnvelope("en_US");
$payRequest->requestEnvelope = $requestEnvelope;
$payRequest->actionType = "PAY";
$payRequest->cancelUrl = "http://example.com/";
$payRequest->returnUrl = "http://example.com/";
$payRequest->currencyCode = "USD";
$payRequest->ipnNotificationUrl = "http://example.com/";

$sdkConfig = array(
    "mode" => "sandbox",
    "acct1.UserName" => "general_api1.example.com",
    "acct1.Password" => "example",
    "acct1.Signature" => "example",
    "acct1.AppId" => "example"
);

$adaptivePaymentsService = new \PayPal\Service\AdaptivePaymentsService($sdkConfig);
$payResponse = $adaptivePaymentsService->Pay($payRequest);

if ($payResponse->responseEnvelope->ack == "Success")
{
    header('Location: ' . 'https://www.paypal.com/webscr?cmd=_ap-payment&paykey=' . $payResponse->payKey);
}
else{
    header('Location: ' . 'http://example.com/');
}
`

Hope that it will help you guys, if you have any questions let me know ;)

**Comment by Omnitasker** [comment]
I think it is not matter of code, can you please tell us more about your server configuration, curl version,  php version etc. I would like to compare config with mine.

**Comment by AnatolyAstapov** [comment]
paypal/sdk-core-php  - deprecated 
need use paypal/rest-api-sdk-php
composer "paypal/rest-api-sdk-php" : "v1.6.3"
and update openssl and php curl,
but in MAMP i can`t update, v4 coming soon 

my new work code 

`$apiContext = new ApiContext(new OAuthTokenCredential(
                $this->config->paypal["client_id"], $this->config->paypal["client_secret"])
        );

        $apiContext->setConfig(array(
            'service.EndPoint'=> $this->config->paypal["end_point"],
            "log.FileName"  => $this->config->application->logDir.'paypal.log'
        ));

        $payer = new Payer();
        $payer->setPaymentMethod("paypal");

        $item1 = new Item();
        $item1->setName($payName)
            ->setCurrency(strtoupper($currency))
            ->setQuantity(1)
            ->setSku(mt_rand(151323,mt_getrandmax())) // Similar to `item_number` in Classic API
            ->setPrice($amount);

        $itemList = new ItemList();
        $itemList->setItems(array($item1));

        $Amount = new Amount();
        $Amount->setCurrency(strtoupper($currency))
            ->setTotal($amount);

        $transaction = new Transaction();
        $transaction->setAmount($Amount)
            ->setItemList($itemList)
            ->setDescription("Payment description")
            ->setInvoiceNumber(uniqid());
        $redirectUrls = new RedirectUrls();
        $redirectUrls->setReturnUrl($this->config->paypal["redirect_url"]."?".\Driver::BuildRequest(["success" => true ]))
            ->setCancelUrl($this->config->paypal["redirect_url"]."?".\Driver::BuildRequest(["success" => false ]));

        $payment = new Payment();
        $payment->setIntent("sale")
            ->setPayer($payer)
            ->setRedirectUrls($redirectUrls)
            ->setTransactions(array($transaction));


        try {
            $payment->create($apiContext);

            return $payment->getApprovalLink();

            $result =  json_decode($payment);

            if(isset($result->links[1]->href)) {
                return $result->links[1]->href;
            }

        } catch (\Exception $ex) {
            $this->paypal_error->error("Exception: ".$ex->getMessage());
           return null;
        }`

**Comment by Omnitasker** [comment]
Thank for  the anwser, but I'm still confused, I used this REST API until now, and it worked fine, but now  I have need for using adaptive payments, and adaptive payments automatically downloads paypal/sdk-core-php and works with that library, and I think there are no options in REST API for adaptive payments.
Did you actually get to work with adaptive payments with REST API ?

**Comment by AnatolyAstapov** [comment]
if you problem in ssl v3, need update openssl + curl
if your server system debian \ ubuntu 
go to terminal and run
`php -i | grep OpenSSL`
ex `OpenSSL Library Version => OpenSSL 1.0.1k 8 Jan 2015
OpenSSL Header Version => OpenSSL 1.0.1k 8 Jan 2015`

if you Version <  1.0 need upgrade 

`sudo apt-get update && sudo apt-get upgrade
sudo apt-get install openssl libssl-dev
apt-cache policy openssl libssl-dev
sudo apt-get upgrade php5-curl`

**Comment by Omnitasker** [comment]
Here is what server outputs:
SSL Version => OpenSSL/1.0.1e
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version => OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL support => enabled

Its 1.0.1, but version e, and year 2013, so maybe it really need new update. But in post above I wrote I tested paypal connection with code :
`php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch));'`

from [https://github.com/paypal/TLS-update](https://github.com/paypal/TLS-update)

and I got response PayPal_Connection_OK , I guess error should have been there.

Anyway, thank you very much.

**Comment by vikramrawat11** [comment]
Hi,

please can you give me working script I getting errro :+1: 

SDK Exception
Type 	PPConnectionException
Message 	error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Detailed message 	Error connecting to https://svcs.sandbox.paypal.com/AdaptivePayments/Pay

Please help me its very urgent for me.

Thanks

**Comment by Omnitasker** [comment]
Hi, after I've checked my server is properly configured, I came accros this line of code that solved my problem with handshake: 
`PayPal\Core\PPHttpConfig::$DEFAULT_CURL_OPTS[CURLOPT_SSLVERSION] = 6;`

before making any calls. 
I hope it will help you too

**Comment by vikramrawat11** [comment]
Hi ,

I am getting same issue, please can you give me working script or script url.

currently PPHttpConfig:

public static $DEFAULT_CURL_OPTS = array(
		CURLOPT_SSLVERSION => 6,
		CURLOPT_CONNECTTIMEOUT => 10,
		CURLOPT_RETURNTRANSFER => TRUE,
		CURLOPT_TIMEOUT        => 60,	// maximum number of seconds to allow cURL functions to execute
		CURLOPT_USERAGENT      => 'PayPal-PHP-SDK',
		CURLOPT_HTTPHEADER     => array(),
		CURLOPT_SSL_VERIFYHOST => 2,
		CURLOPT_SSL_VERIFYPEER => 1,
		CURLOPT_SSL_CIPHER_LIST => 'TLSv1',
	);

Please give me any idea to solve it, its urgent
Thanks

**Comment by Omnitasker** [comment]
Here is the whole script I used but I am not sure if it will help you,

**Comment by Omnitasker** [comment]
Version of php sdk I used is "v3.6.106". To be honest I am out of ideas, assuming that you tried everything from above like checking your server configuration and testing it with 

`php -r '$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch));'`

**Comment by vikramrawat11** [comment]
HI 

I run below code and get bool(false)
$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); var_dump(curl_exec($ch));

Please can you suggest me.

Thanks

**Comment by ppmtscory** [comment]
@vikramrawat11 were you able to get your system updated so that you could get rid of the handshake error in the Sandbox environment?  If not, what is the full error that shows in the `var_dump(curl_exec($ch));`?

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.

**Comment by imalhasaranga** [comment]
I had the same issue recently and was able to fix it by doing following 

`PayPalHttpConfig::$DEFAULT_CURL_OPTS[CURLOPT_SSLVERSION] = 4;`

**Comment by imalhasaranga** [comment]
I Recently Had this problem and here was the fix that worked for me. 

`PayPal\Core\PPHttpConfig::$DEFAULT_CURL_OPTS[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1;`

**Comment by MikeOtown** [comment]
PayPal\Core\PPHttpConfig::$DEFAULT_CURL_OPTS[CURLOPT_SSLVERSION] = 6;

worked for me

**Comment by faisalim048** [comment]
**PayPal\Core\PPHttpConfig::$DEFAULT_CURL_OPTS[CURLOPT_SSLVERSION] = 6;**

yeah this one also worked for me.
