### ISSUE TITLE
Warning: PayPal\Auth\OAuthTokenCredential

### ISSUE THREAD

**Issue by googlle** [paypal/adaptivepayments-sdk-php#65]
Hi. Is it normal?
Warning: Ambiguous class resolution, "PayPal\Auth\OAuthTokenCredential" was found in both "../vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php" and "../vendor/paypal/sdk-core-php/lib/PayPal/Auth/OAuthTokenCredential.php", the first will be used.

I use in composer.json
"paypal/adaptivepayments-sdk-php": "*",
"paypal/rest-api-sdk-php": "*",

**Comment by ppmtscory** [comment]
It looks to me like you are trying to use 2 different SDKs and therefore there may be duplication.  If you are using this SDK, just use this one, and the same if you want to use the REST PHP SDK instead.

**Comment by googlle** [comment]
But I need to use both

**Comment by ppmtscory** [comment]
What is your use case?  Why do you need both SDKs in a single project?

**Comment by googlle** [comment]
It is necessary to receive payments, and send in the project

**Comment by ppmtscory** [comment]
@googlle can you provide any more detail as to _how_ you are receiving and sending?  Based on your comment, you should be able to do everything via the Adaptive Payments SDK and so I'm unsure as to why you need the REST SDK.  What features are you using from each that makes you believe that you need both?

**Comment by jaypatel512** [comment]
Hey @googlle !

Can you please update your dependencies now, you should have a newer version of sdk-core-php [v3.3.0](https://github.com/paypal/sdk-core-php/releases/tag/3.3.0).

Please run `composer clear-cache` if that does not happen. Confirm if that fixes your problem. Also, please explain your scenario on why you need both SDKs as asked by @ppmtscory , as it helps us understand our use case, and any shortcomings, that we can fix.

**Comment by googlle** [comment]
@jaypatel512 thanks, it works fine

**Comment by googlle** [comment]
@ppmtscory Can I receive payment on site and send to user payment via Adaptive Payments SDK?
