### ISSUE TITLE
Duplicate folders

### ISSUE THREAD

**Issue by muratyaman** [paypal/adaptivepayments-sdk-php#66]
lib/PayPal/Types/AP
lib/PayPal/Types/ap  ==> this has additional files PhoneNumber.php and ShippingAddressInfo.php

lib/PayPal/Types/Common
lib/PayPal/Types/common

Please fix it.

**Comment by neo22s** [comment]
Correct, and all duplicated files with same content, why?

**Comment by oniric85** [comment]
Just noticed this after I switched to case sensitive file system. Seems like a bad commit.

**Comment by jaypatel512** [comment]
Fixed in https://github.com/paypal/adaptivepayments-sdk-php/pull/53
