### ISSUE TITLE
Can't install because of ZendGuardLoader.so

### ISSUE THREAD

**Issue by NicolasTaulard** [paypal/adaptivepayments-sdk-php#68]
hello, i've typed this command

curl -k -L https://raw.githubusercontent.com/paypal/adaptativepayments-sdk-php/stable-php5.3/samples/install.php | php

but i have this message

Failed loading /usr/php/54/usr/lib64/php/modules/ZendGuardLoader.so:  /usr/php/54/usr/lib64/php/modules/ZendGuardLoader.so: undefined symbol: zend_new_interned_string
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     39      0 --:--:-- --:--:-- --:--:--    49
Content-type: text/html

Not Found

**Comment by ppmtscory** [comment]
Please try it with the correct URLs from below and either reopen or open a new issue if the error persists.
```
curl -L https://raw.github.com/paypal/adaptivepayments-sdk-php/stable-php5.3/samples/install.php | php    
        OR        
wget  https://raw.github.com/paypal/adaptivepayments-sdk-php/stable-php5.3/samples/install.php
php install.php
```
