### ISSUE TITLE
Payment Session Expired

### ISSUE THREAD

**Issue by jagroop** [paypal/adaptivepayments-sdk-php#73]
After Creating adaptive payment service when user get redirected to 

https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=PAY_KEY

getting this error every time

> Your payment session has expired. Please return to the participating website and try again.

Code:
```php
<?php
$payRequest = new PayRequest();

$receiver = array();
$receiver[0] = new Receiver();
$receiver[0]->amount = "1.00";
$receiver[0]->email = "reciver1@paypal.com";
 				
$receiver[1] = new Receiver();
$receiver[1]->amount = "2.00";
$receiver[1]->email = "reciver2@paypal.com";
$receiver[1]->primary = "true";
$receiverList = new ReceiverList($receiver);
$payRequest->receiverList = $receiverList;

$requestEnvelope = new RequestEnvelope("en_US");
$payRequest->requestEnvelope = $requestEnvelope; 
$payRequest->actionType = "PAY";
$payRequest->cancelUrl = "http://localhost/dev/paypal/cancel.php?cancel=true";
$payRequest->returnUrl = "http://localhost/dev/paypal/success.php?success=true";
$payRequest->currencyCode = "USD";
$payRequest->ipnNotificationUrl = "http://replaceIpnUrl.com";

$sdkConfig = array(
	"mode" => "sandbox",
	"acct1.UserName" => "foobar.paypal.com",
	"acct1.Password" => "XXXXX",
	"acct1.Signature" => "XXXXXX",
	"acct1.AppId" => "APP-80W284485P519543T"
);

$adaptivePaymentsService = new AdaptivePaymentsService($sdkConfig);
$payResponse = $adaptivePaymentsService->Pay($payRequest); 
header("Location:https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=".$payResponse->payKey);
```

**Comment by ppmtscory** [comment]
You're most likely getting an error in your `$payResponse` due to the receivers not being valid Sandbox accounts.  Therefore, the `paykey` that you're assigning in the header redirect isn't valid.

**Comment by ppmtscory** [comment]
You're most likely getting an error in your `$payResponse` due to the receivers not being valid Sandbox accounts.  Therefore, the `paykey` that you're assigning in the header redirect isn't valid.

**Comment by jagroop** [comment]
@ppmtscory No, both recievers are valid !! i have checked it !!

**Comment by ppmtscory** [comment]
Is there a typo in your snippet you provided?  The below receiver emails do not exist in our Sandbox environment...
`$receiver[0]->email = "reciver1@paypal.com";`
`$receiver[1]->email = "reciver2@paypal.com";`

**Comment by jagroop** [comment]
@ppmtscory 
Hello mate,
No there is no type in the snippet i provided?
actually the wired part is that ... i am doing the same thing with [adaptive-payments](https://github.com/jagroop/paypal-adaptive)
and it works like charm :/

**Comment by ppmtscory** [comment]
Those receivers are not valid.  I get the same exact error with your code.  Also, you can tell that there's an issue because there's no paykey in the redirect URL on the PayPal page....
```
PayResponse Object
(
    [responseEnvelope] => ResponseEnvelope Object
        (
            [timestamp] => 2016-04-11T09:50:58.875-07:00
            [ack] => Failure
            [correlationId] => d7ad0dc4f5bf0
            [build] => 20420247
        )

    [payKey] => 
    [paymentExecStatus] => 
    [payErrorList] => 
    [paymentInfoList] => 
    [sender] => 
    [defaultFundingPlan] => 
    [warningDataList] => 
    [error] => Array
        (
            [0] => ErrorData Object
                (
                    [errorId] => 520009
                    [domain] => PLATFORM
                    [subdomain] => Application
                    [severity] => Error
                    [category] => Application
                    [message] => Account Account not found. Unilateral receiver not allowed in chained payment is restricted
                    [exceptionId] => 
                    [parameter] => Array
                        (
                            [0] => ErrorParameter Object
                                (
                                    [name] => 
                                    [value] => Account not found. Unilateral receiver not allowed in chained payment
                                )

                        )

                )

        )

)
```

**Comment by ppmtscory** [comment]
When I use valid receiver accounts, your code works just fine....
![screen shot 2016-04-11 at 11 53 59 am](https://cloud.githubusercontent.com/assets/6306449/14435175/1ba6fde0-ffdc-11e5-874f-4be10c754a24.png)

**Comment by ppmtscory** [comment]
You'll need to go to developer.paypal.com, login, click dashboard, click accounts under sandbox, and then create yourself a few accounts to play with.  These are the emails that you'll need to use for your receivers in your code.

**Comment by alrubeey** [comment]
ppmtscory Please i need this script of payment paypal

**Comment by alrubeey** [comment]
of u can send me your email address

**Comment by xiaoleih41** [comment]
@alrubeey  I am not sure what script you were referring to. The above code was the one used in the issue.  Please create a new issue if you have any specific question or contact PayPal technical support if you are looking for integration recommendation. I am locking this conversation as the original issue has been solved.
