### ISSUE TITLE
Does this work with PHP 7? 

### ISSUE THREAD

**Issue by HallofFamer** [paypal/adaptivepayments-sdk-php#77]
Can I upgrade to PHP 7 and be sure that Paypal API is still working?

**Comment by jaypatel512** [comment]
Hey @HallofFamer !

We have not tested it yet, however, I will run a quick test, and get back to you.

**Comment by jaypatel512** [comment]
Hey @HallofFamer !

We were able to successfully test it on a PHP 7 version on Mac OS.
