### ISSUE TITLE
Run composer error

### ISSUE THREAD

**Issue by vutungf** [paypal/adaptivepayments-sdk-php#79]
Hi,

I run "curl -L https://raw.github.com/paypal/adaptivepayments-sdk-php/stable-php5.3/samples/install.php | php" and get error 404: Not Found

**Comment by jaypatel512** [comment]
You should just use `composer install` for installing these dependencies. The install.php file was created as an alternative to composer install.

If you have to use it, you can find it at https://raw.githubusercontent.com/paypal/adaptivepayments-sdk-php/master/samples/install.php
