### ISSUE TITLE
How do we get on the platform?

### ISSUE THREAD

**Issue by arun057** [paypal/adaptivepayments-sdk-php#82]
I am seeing this on every page related to Adaptive Payments: 

> Adaptive Payments is now a limited release product. It is restricted to select partners for approved use cases and should not be used for new integrations without guidance from PayPal.

Is there a process to get approved? There doesnt seem to be much information about it out there.

**Comment by bluk** [comment]
Please contact [PayPal Support](https://www.paypal.com/us/selfhelp/home) for the answer to this question. I would recommend looking at other solutions as mentioned on the [blog post announcement](https://devblog.paypal.com/adaptive-payments-limited-release/) if possible.

**Comment by karinehsu** [comment]
@arun057 Did you ever get approved for Adaptive Payments or did you find a workaround?

**Comment by arun057** [comment]
Yeah got approved, but they are deprecating the api. We never got around to actually using it.

**Comment by karinehsu** [comment]
What did you guys end up using instead? Express Checkout + Payouts API? Downside is the double transaction fees. I've been looking through the documentation and I've been struggling to find a workaround.

**Comment by arun057** [comment]
A combination of things. You should check out WePay
