### ISSUE TITLE
Change description on payment summary

### ISSUE THREAD

**Issue by hmartinsceven** [paypal/adaptivepayments-sdk-php#84]
Hello,

How can I change the description of the payment summary for some dynamic text.

Eventually it will be a super easy set this, but I do not have much experience with Paypal integrations.

I am playing this in the Pay.php file of the SDK.

Thanks in advance.

![paymentsummary](https://cloud.githubusercontent.com/assets/3170222/21855797/8a6cf27a-d817-11e6-8e62-ddd310c22195.png)

**Comment by pp-randy** [comment]
@hmartinsceven I apologize for the delay.  How are you wanting to accept payments?  If it is PayPal payments to your own merchant account I would recommend a different SDK for you.

**Comment by pp-randy** [comment]
This is harder to do with adaptive payments.  Please provide more information and will try to guide you in the best direction.
