### ISSUE TITLE
Sanbox to Live credentials error message

### ISSUE THREAD

**Issue by Goletrax** [paypal/adaptivepayments-sdk-php#85]
This is the error message we get after switching from sanbox to live. Sanbox works fine, but live credentials is giving us the following error:   CAN SOMEONE HELP US WITH THIS PLEASE?

"acct1.UserName" => "USERNAME",
                "acct1.Password" => "PASSWORD",
                "acct1.Signature" => "SIGNATURE",
                "acct1.AppId" => "APPID"

PAYPAL RESPONSE

PayPal\Types\AP\PayResponse Object
(
    [responseEnvelope] => PayPal\Types\Common\ResponseEnvelope Object
        (
            [timestamp] => 2017-01-09T08:08:42.097-08:00
            [ack] => Failure
            [correlationId] => a5b01cbf11ce
            [build] => 27237463
        )

    [payKey] => 
    [paymentExecStatus] => 
    [payErrorList] => 
    [paymentInfoList] => 
    [sender] => 
    [defaultFundingPlan] => 
    [warningDataList] => 
    [error] => Array
        (
            [0] => PayPal\Types\Common\ErrorData Object
                (
                    [errorId] => 520002
                    [domain] => PLATFORM
                    [subdomain] => Application
                    [severity] => Error
                    [category] => Application
                    [message] => Internal Error
                    [exceptionId] => 
                    [parameter] => 
                )

        )

)

**Comment by pp-randy** [comment]
Are you still getting this internal error?

**Comment by pp-randy** [comment]
Closing due to lack of response
