### ISSUE TITLE
I have find a Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [paypal/adaptivepayments-sdk-php#87]
Hello:
I have find a Reflected XSS vulnerability in this sdk.

The vulnerability exists due to insufficient filtration of user-supplied data in “payKey” HTTP REQUEST parameter that will be passed to “adaptivepayments-sdk-php-master\samples\SetPaymentOptions.php”. The infected source code is line 24, there is no protection on $_REQUEST['payKey']; if $_REQUEST['payKey'] contains evil js code, line 24 will trigger untrusted code to be executed on the browser side.
![image](https://cloud.githubusercontent.com/assets/1484292/23159831/3facf9c0-f85f-11e6-9b92-b473bda03759.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/adaptivepayments-sdk-php-master/samples/SetPaymentOptions.php?payKey="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![image](https://cloud.githubusercontent.com/assets/1484292/23159996/db5b7108-f85f-11e6-846f-f6856e558e51.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech
Email: jgj212@gmail.com

**Comment by pp-randy** [comment]
Adding internal tracking: BTDXCLTS-283
