### ISSUE TITLE
This payment request must be authorized by the sender

### ISSUE THREAD

**Issue by sachy123** [paypal/adaptivepayments-sdk-php#91]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Why I cannot make payment from my website to the users? I have business account.

responseEnvelope.timestamp=2017-05-26T07%3A27%3A03.530-07%3A00&responseEnvelope.ack=Failure&responseEnvelope.correlationId=ba84809c175f6&responseEnvelope.build=32250686&error(0).errorId=550001&error(0).domain=PLATFORM&error(0).subdomain=Application&error(0).severity=Error&error(0).category=Application&error(0).message=This+payment+request+must+be+authorized+by+the+sender

**Comment by xiaoleih41** [comment]
Are you trying to do **payouts** instead of receiving payments from others? If that's the case, please consider to use REST [payout API](https://developer.paypal.com/docs/integration/direct/payouts/?mark=payout) for this.

**Comment by sachy123** [comment]
Yes I am doing Payouts to 2 persons at same time.

**Comment by sachy123** [comment]
BTW I am using adaptive payment SDK. The following code.
`$execute_response=$adaptivePaymentsService->ExecutePayment($executePaymentRequest);`
and receiver list is an array of 2 users.

**Comment by xiaoleih41** [comment]
Can you send me the full API request you sent to PayPal masking all the sensitive information such as password etc.?  When you make the call, did you specify your email in the `senderEmail` field to make it implicit just like the instruction provided [here](https://developer.paypal.com/docs/classic/api/adaptive-payments/Pay_API_Operation/)?

**Comment by sachy123** [comment]
it worked!!
Thanks a lot. BTW why do I have to specify senders email? isnt it already known from my config file?
