### ISSUE TITLE
"Invalid credentials for" at ConvertCurrency method

### ISSUE THREAD

**Issue by emanu11** [paypal/adaptivepayments-sdk-php#92]
### General information

* SDK/Library version: PayPalAdaptivePaymentsSDK/2.15.117
* Environment: sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Hello,
I am trying to convert a currency when I am making a payout. The problem is that every time I try to do that, the API responds with "Invalid credentials for" when I am calling the `service.ConvertCurrency(request, "Merchant_api1.navatec.de");`

Here is the code I am trying to use

` List<CurrencyType> currencies = new List<CurrencyType>()
            {
                new CurrencyType(fromCurrency,Convert.ToDecimal(amount))
            };

            CurrencyList baseAmountList = new CurrencyList(currencies);

            CurrencyCodeList convertToCurrencyList = new CurrencyCodeList(new List<string> { toCurrnecy });

            ConvertCurrencyRequest request = new ConvertCurrencyRequest(
                new RequestEnvelope("en_US"), baseAmountList, convertToCurrencyList);

            AdaptivePaymentsService service = null;
            ConvertCurrencyResponse response = null;
            try
            {
                // Creating service wrapper object to make an API call and loading
                // configuration map for your credentials and endpoint
                service = new AdaptivePaymentsService(PayPalConfig.GetConfig());
                response = service.ConvertCurrency(request, "Merchant_api1.navatec.de");

            }
            catch (System.Exception e)
            {
                log.Error(e.Message);
                WriteLine(e.Message);
                WriteLine(e.InnerException);
                WriteLine(e);
                return;
            }`

**Comment by xiaoleih41** [comment]
Do you have a `debugId` that you can share with us?

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have further questions.
