### ISSUE TITLE
Using preapproval

### ISSUE THREAD

**Issue by angular013** [paypal/adaptivepayments-sdk-php#94]
Hello and good day. I am working on an e-commerce website , currently i have paypal express checkout on that store . I want to integrate pre-approval and future payment on the store so that , if a customer returns in future to buy something else from my store then i do not want to take him to the whole steps of checkout rather i want to charge him automatically. maybe we will add subscriptions also in future in our store , so need help on how to integrate with php .
So far this is my code.....any help would be much appreciated ( i have a sandbox account for testing also )
I have downloaded adaptive payments SDK using composer

`require 'vendor/autoload.php';
$config = array(
       'mode' => 'sandbox', // sandox or live
       'acct1.UserName' => 'my-username',
       'acct1.Password' => 'my-password',
	   "acct1.Signature" => "my-signature"
    );
	
$service = new AdaptivePaymentsService($config);	`

I have read that this library is deprecated in another previous issue. but only this adaptive payments library is mentioned on this link:
https://developer.paypal.com/docs/classic/lifecycle/adaptive-payments/sdks/

by the way i also have this library installed ;
https://github.com/paypal/PayPal-PHP-SDK

but cannot seem to find the pre-approved and future payment there.

**Comment by xiaoleih41** [comment]
Future payment and adaptive payment API have been deprecated. This version of REST API doesn't support flexible amount billing agreement. I would strongly suggest you to use Braintree SDK vault feature instead. It supports not only direct credit card processing but also PayPal payment processing for fixed amount or flexible amount billing agreement.

**Comment by angular013** [comment]
@xiaoleih41 

Thanks for guidance. So i integrated the braintree library , currently testing using sandbox account , linked it with my sandbox paypal account . and it working fine . but some options are missing in braintree paypal integration ,which were available in direct paypal express checkout .

I have posted the issue on braintree SDK issues page also because cant seem to find where to post this issue. here is the link to the issue;

https://github.com/braintree/braintree_php/issues/197

I will greatly appreciate , if you can take a look at the above link issue. and suggest a solution. Thanks

**Comment by xiaoleih41** [comment]
I can see that your question was answered in Braintree php repository. Please follow up with them if you have any further questions.
