### ISSUE TITLE
Invalid request parameter : institutionId

### ISSUE THREAD

**Issue by yogeshg1** [paypal/adaptivepayments-sdk-php#95]
Hello,
I want order detail description in our paypal business account, so that I can get which product is purchased and its quantity.
For that I am  using setPaymentOption Adaptive payment API for sending order details to paypal.

"$service = new AdaptivePaymentsService(Configuration::getAcctAndConfig());
$response = $service->SetPaymentOptions($setPaymentOptionsRequest);" 
I am executing this API call after Pay API suceessful response.
"$response = $service->SetPaymentOptions($setPaymentOptionsRequest);"

But getting error as Invalid request parameter : institutionId.
Where do i Find institutionId in PayPal?

Thanks

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
