### ISSUE TITLE
experienceProfileId on adaptivePayment

### ISSUE THREAD

**Issue by scadox** [paypal/adaptivepayments-sdk-php#96]
Hi Paypal team,

i have found on class Payment(), the method ::setExperienceProfileId() for set payment experience profile for express payment.

If is possible append similar method to adaptivepayments-sdk in PayRequest() example for push parameter (experience_profile_id) to Pay?

Cordialement,
Matthew

**Comment by xiaoleih41** [comment]
@scadox  We are deprecating adpative payment API. Therefore there will be no enhancement to this SDK.  Please look into [PayPal marketplace API](https://developer.paypal.com/docs/marketplaces/pp4mp/) to see if it fits your need.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.

**Comment by scadox** [comment]
Thank you for response, i try get new API from marketplace.

Cordialement,
Matthew
