### ISSUE TITLE
Missing files in use statements in AdaptivePaymentsService.php

### ISSUE THREAD

**Issue by stefan-stoj** [paypal/adaptivepayments-sdk-php#97]
### General information

* AdaptivePayments SDK version: Current version
* PayPal-PHP-SDK version: 1.12.0

### Issue description

NOTE: I followed the Direct Download method for the SDKs mentioned below as a ZIP file from GitHub and merged the PayPal folders. **I did not use Composer to install the SDKs**

`adaptivepayments-sdk-php/lib/PayPal/Service/AdaptivePaymentsService.php` is missing files that are `use`d. 
I downloaded the current PayPal-PHP-SDK(https://github.com/paypal/PayPal-PHP-SDK) and merged the `lib/PayPal/` folders which fixed some of the missing files, but not all.
After merging the files from the official master SDK and the AdaptivePayments SDK `AdaptivePaymentsService.php` is still missing the following files:
```
use PayPal\Common\PPApiContext;
use PayPal\Core\PPMessage;
use PayPal\Core\PPBaseService;
use PayPal\Core\PPUtils;
use PayPal\Handler\PPPlatformServiceHandler;
```
From where can I download the missing files?

**Comment by bluk** [comment]
You are missing the files from https://github.com/paypal/sdk-core-php .  Hope that helps.
