### ISSUE TITLE
Adaptive payment IPN returns only primary recivers details and amount transaction[n] is missing 

### ISSUE THREAD

**Issue by vishnu-the-developer** [paypal/adaptivepayments-sdk-php#99]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by bluk** [comment]
It seems that your issue is specific to the IPN payload that you are receiving. Please contact [PayPal Technical Support](https://developer.paypal.com/support/) for assistance with your issue.
